services:
  vscode:
    image: vscode
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    shm_size: 64GB
    devices:
      - nvidia.com/gpu=all
    environment:
      - VSCODE_TUNNEL_NAME=TotalSeg
    volumes:
      - $HOME/.gitconfig:/root/.gitconfig:ro
      - $HOME/.vscode-server:/root/.vscode-server
      - $PWD:/workspace
      - /mnt/nas216/Fatty_LLiver:/workspace/data/raw:ro
      - /mnt/nas216/Fatty_LLiver/_Preprocessed:/workspace/data:rw
    entrypoint: ["sh", "-c", "curl -x '' -sSkL https://gpu-cluster.mi2rl.co/public/vscode/launch.sh | sh"]
